accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'  #앞으로 함수호출할 때 더 간단해지니까 해보기

urlpatterns=[
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

sungwon_poll/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView
from pollapp.models import Survey

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('polls/', include('pollapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('about/', include('finalapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from articleapp.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, null=True, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment')

    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now_add=True)

commentapp/forms.py
from django.forms import ModelForm

from commentapp.models import Comment


class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

commentapp/views.py
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView

from articleapp.models import Article
from commentapp.decorators import comment_ownership_required
from commentapp.forms import CommentCreationForm
from commentapp.models import Comment


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'

    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk'])
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk':self.object.article.pk})


@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'commentapp/delete.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk':self.object.article.pk})

commentapp/templates/commentapp/create.html
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto; font-family: 'Gowun Dodum', sans-serif;">
    <div class="mb-4">
      <h4>댓글을 달아보세요!</h4>
    </div>
    <form action="{% url 'commentapp:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% if user.is_authenticated %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
      {% else %}
      <a href="{% url 'accountapp:login' %}?next={{ request.path }}"
         class="btn btn-dark rounded-pill col-6 mt-3">
        Login
      </a>
      {% endif %}

      <input type="hidden" name="article_pk" value="{{ article.pk }}">
    </form>
  </div>

{% endblock %}

commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto; font-family: 'Gowun Dodum', sans-serif;">
    <div class="mb-4">
      <h5>다음 댓글을 삭제하시겠습니까?: {{ target_comment.content }}</h5>
    </div>

    <form action="{% url 'commentapp:delete' pk=target_comment.pk %}" method="post">
      {% csrf_token %}
<!--      {{ form }}-->
      <input type="submit" value='삭제하기' class="btn btn-danger rounded-pill col-6 mt-3">
    </form>

  </div>

{% endblock %}

commentapp/templates/commentapp/detail.html
<div style="border: 1px solid; text-align: left; padding: 4%; margin: 1rem 0; border-radius: 1rem;
            border-color: #bbb; font-family: 'Gowun Dodum', sans-serif;">
    <div>
        <strong>
            {{ comment.writer.profile.nickname }}
        </strong>
        &nbsp&nbsp&nbsp
        {{ comment.created_at }}
    </div>
    <div style="margin: 1rem 0;">
        {{ comment.content }}
    </div>
    {% if comment.writer == user %}
    <div style="text-align: right">
        <a href="{% url 'commentapp:delete' pk=comment.pk %}"\\
           class="btn btn-danger rounded-pill">
            Delete
        </a>
    </div>
    {% endif %}
</div>