accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'  #앞으로 함수호출할 때 더 간단해지니까 해보기

urlpatterns=[
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete')
]

finalapp/urls.py
from django.urls import path

from finalapp import views

app_name = 'finalapp'

urlpatterns=[
    path('service/',views.about, name='service'),
    path('terms/', views.terms_of_use, name='terms'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

pollapp/urls.py
from django.urls import path

from pollapp import views

app_name='pollapp'

urlpatterns=[
    path('',views.home, name='home'),
    path('save',views.save_survey),
    path('results', views.show_result),

    # ================================================
    path('list/', views.list, name='list'),
    ]

sungwon_poll/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView
from pollapp.models import Survey

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('polls/', include('pollapp.urls')),
    path('likes/', include('likeapp.urls')),
    path('about/', include('finalapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>

    {% include 'header.html' %}

    <hr>

    {% for message in messages %}

    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5 my-3">
            {{ message }}
        </div>
    </div>

    {% endfor %}

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
  <div class="django_footer">
        <div class="django_footer_button">
            <a href="{% url 'finalapp:service' %}" class="poll_header_nav">
                <span>서비스 소개</span>
             </a>
            <span>|</span>
            <a href="{% url 'finalapp:terms' %}" class="poll_header_nav">
                <span>이용약관</span>
             </a>
        </div>
        <div style="margin-top: 1rem;">
            <h6 class="django_logo">공론장</h6>
            <h8 class="django_logo">contact: tjddnjs2013@gmail.com</h8>
        </div>
    </div>

templates/head.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Poll</title>

    <!-- BootStrap Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Google Fonts Link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">

    <!-- GOOGLE MATERIAL ICONS LINK  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

</head>

templates/header.html
    <div class="django_header">
          <div>
            <h1 class="django_logo"><a href="{%url 'home' %}">공론장</a></h1>
          </div>

          <div class="poll_header_navbar">
             <a href="{% url 'pollapp:home' %}" class="poll_header_nav">
                <span>설문조사</span>
             </a>
             <a href="{% url 'articleapp:list' %}" class="poll_header_nav">
                <span>게시글방</span>
             </a>
             <a href="{% url 'projectapp:list' %}" class="sungwon_header_nav">
                <span>토론방</span>
             </a>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="poll_header_nav">
                <span>로그인</span>
            </a>
            <a href="{% url 'accountapp:create' %}" class="poll_header_nav">
                <span>회원가입</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="poll_header_nav">
                <span>내페이지</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="poll_header_nav">
                <span>로그아웃</span>
            </a>
            {% endif %}
          </div>
    </div>